const leads = [
  {
    "business": "string",
    "confirmed": "2019-11-07",
    "creation_timestamp": "2019-11-07T17:43:25Z",
    "customer_name": "string",
    "customer_phone": "string",
    "email": "user@example.com",
    "kind": "web",
    "lead_id": 0,
    "mobile_phone": "string",
    "partner_id": 0,
    "sales_person": "string",
    "sold": "2019-11-07",
    "source": "string",
    "status": "string"
},
{
  "business": "string",
  "confirmed": "2019-11-07",
  "creation_timestamp": "2019-11-07T17:43:25Z",
  "customer_name": "string",
  "customer_phone": "string",
  "email": "user@example.com",
  "kind": "web",
  "lead_id": 0,
  "mobile_phone": "string",
  "partner_id": 0,
  "sales_person": "string",
  "sold": "2019-11-07",
  "source": "string",
  "status": "string"
}
]

export const accounts = [{
  "address_city": "string",
  "address_country": "string",
  "address_line_four": "string",
  "address_line_one": "string",
  "address_line_three": "string",
  "address_line_two": "string",
  "address_post_code": "string",
  "address_region": "string",
  "bank_acc_no": "string",
  "bill_cycle": "C1",
  "business_name": "string",
  "confirmed": "2019-11-07",
  "creation_timestamp": "2019-11-07T17:43:24Z",
  "credit_control_status": "string",
  "email_address": "user@example.com",
  "escalated": true,
  "escalated_text": "string",
  "first_name": "string",
  "id": 0,
  "last_changed": "2019-11-07T17:43:24Z",
  "last_name": "string",
  "leads": [leads[0], leads[1]],
  "mobile_number": "string",
  "monthly_payment_reference": "string",
  "payment_method": "string",
  "phone_number": "string",
  "reference": "string",
  "sort_code": "string"
},{
  "address_city": "string",
  "address_country": "string",
  "address_line_four": "string",
  "address_line_one": "string",
  "address_line_three": "string",
  "address_line_two": "string",
  "address_post_code": "string",
  "address_region": "string",
  "bank_acc_no": "string",
  "bill_cycle": "C1",
  "business_name": "string",
  "confirmed": "2019-11-07",
  "creation_timestamp": "2019-11-07T17:43:24Z",
  "credit_control_status": "string",
  "email_address": "user@example.com",
  "escalated": true,
  "escalated_text": "string",
  "first_name": "string",
  "id": 0,
  "last_changed": "2019-11-07T17:43:24Z",
  "last_name": "string",
  "leads": [leads[0], leads[1]],
  "mobile_number": "string",
  "monthly_payment_reference": "string",
  "payment_method": "string",
  "phone_number": "string",
  "reference": "string",
  "sort_code": "string"
}];

